services:
  db:
    image: postgres:15
    container_name: tmzprosae_db
    restart: always
    environment:
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: password
      POSTGRES_DB:       TMZproSAE
    ports:
      - "5433:5432"
    volumes:
      - tmzprosae_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d TMZproSAE"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: ztmprosae/group-trip-planner:latest
    container_name: tmzprosae_api
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/TMZproSAE
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/code/app


